### ISSUE TITLE
Modify View to Display Sonarr Information

### ISSUE THREAD

**Issue by osu-murphcol** [cs361w2019-osu/sprint1-group-25#53]
Revealed spaces should be indicated by gray squares and revealed ships should be indicated by black squares

**Comment by evanmhm** [comment]
Sonar implemented in PR #56 but colors are not consistent with this issue, either edit the sonar function to make a new attack status of REVEALED and implement in game.js markHits() or close this issue.

**Comment by osu-murphcol** [comment]
Issue completed in #56, #60, #63
